### PR TITLE
1. Change:plugin Name

### PR DESCRIPTION
**Pull request by thetwinhtwe**
2.Insert Contributor
3.Change Tags
4.Change Description By Thet Win Htwe 16/01/2016 12:17

### CODE REVIEW

**Comment by herzcthu** [comment]
contributors name should be wordpress.org username

**Comment by thetwinhtwe** [comment]
I don't know other contributor's wordpress.org username?How to fix it?

**Comment by herzcthu** [comment]
Don't worry they should add themselves.

**Comment by thetwinhtwe** [comment]
Ok Bro.

**Pull request merged**
